import Head from "next/head";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Image from "next/image";
import { useEffect, useState } from "react";

export default function Home() {
  const user = useUser();
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
  }, []);

  if (!isClient) return;

  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-zinc-900 text-slate-50">
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/* layout wrapper */}
        <div className="flex w-full items-start justify-center">
          <div className="flex min-h-screen w-full max-w-6xl flex-col border-x border-slate-900">
            <header>
              <div className="flex w-full flex-col bg-blue-500 text-white">
                {!user.isSignedIn && <SignInButton />}
                {user.isSignedIn && <SignOutButton />}
              </div>
            </header>
            {!user.isSignedIn && (
              <>
                <TopSection />
                <MiddleSection />
                <BottomSection />
              </>
            )}
            {user.isSignedIn && <div> User is signed in</div>}

            {/* layout wrapper */}
          </div>
        </div>
      </div>
    </div>
  );
}

function TopSection() {
  return (
    <section className="flex h-full w-full flex-col gap-4 md:flex-row">
      <div className="flex h-full w-full items-center justify-center gap-2 px-4 py-8 md:py-20 lg:py-40">
        <Image
          priority
          src="/images/Streamsave.svg"
          alt="StreamSave Logo"
          width={1900}
          height={3330}
          className="h-auto w-32 lg:w-80"
        />

        <div className="flex h-full flex-col justify-center gap-2 p-2">
          <div>
            <h1 className="text-2xl font-bold lg:text-5xl">Streamsave</h1>
            <span className="text-sm text-slate-300">fill your show hole</span>
          </div>

          <div className="mt-4 flex items-center justify-center bg-pink-700 px-6 py-2 transition-all hover:scale-105 hover:rounded-md">
            <SignInButton />
          </div>
        </div>
      </div>

      <div className="flex w-full items-center justify-center bg-gradient-to-l from-sky-700 to-transparent py-20 lg:w-2/3 lg:justify-start lg:py-40 lg:pl-12">
        <p className="w-48 text-center font-bold">
          Organize your favorite shows and movies, or discover new ones!
        </p>
      </div>
    </section>
  );
}

function MiddleSection() {
  return (
    <section className="flex w-full flex-col items-center justify-end bg-gradient-to-tr from-pink-700 via-pink-900 to-zinc-900 px-8 py-16 text-white">
      <div className="flex flex-shrink items-center justify-center gap-2 py-8 md:gap-8 lg:gap-16">
        <Image
          className="h-auto w-[30%] md:w-40"
          src="/images/BreakingBad.png"
          alt=""
          width={144}
          height={290}
        />
        <Image
          className="h-auto w-[30%] md:w-40"
          src="/images/TheOffice.png"
          alt=""
          width={144}
          height={290}
        />
        <Image
          className="h-auto w-[30%] md:w-40"
          src="/images/TheLastOfUs.png"
          alt=""
          width={144}
          height={290}
        />
      </div>
      <h2 className="line-clamp-2 text-center text-2xl font-bold leading-normal md:text-3xl lg:text-5xl">
        Your Favorite Shows & Movies
      </h2>
    </section>
  );
}

function BottomSection() {
  return (
    <section className="flex w-full items-center justify-center bg-gradient-to-bl from-sky-600 via-sky-900 to-zinc-900 px-8 py-4 text-white">
      <div className="flex w-2/3 flex-col items-start justify-center gap-8">
        <h2 className="line-clamp-3 text-2xl font-bold leading-normal md:text-3xl lg:text-5xl lg:leading-relaxed">
          Organized The Way You Want
        </h2>
        <div className="flex items-center justify-center bg-pink-700 px-6 py-2 transition-all hover:scale-105 hover:rounded-md">
          <SignInButton />
        </div>
      </div>
      <div className="h-auto w-1/2">
        <Image
          src="/images/mobile-list.png"
          alt="How the user's list looks on a mobile device"
          className="py-12"
          width={260}
          height={336}
        />
      </div>
    </section>
  );
}
