import Head from "next/head";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Image from "next/image";
import { useEffect, useState } from "react";
import Link from "next/link";
import Loading from "~/components/Loading";
import { api } from "~/utils/api";
import type { MovieAPIResult, ShowAPIResult } from "~/utils/types";
import { Swiper, SwiperSlide, useSwiper } from "swiper/react";
import { Navigation, Pagination, Scrollbar, A11y } from "swiper/modules";

import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";
import "swiper/css/a11y";

export default function Home() {
  const user = useUser();
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
  }, []);

  if (!isClient) return;

  if (!user.isLoaded)
    return (
      <div className="flex min-h-screen w-full items-center justify-center bg-zinc-900 text-slate-50">
        <Loading />
      </div>
    );

  return (
    <div className="flex flex-col items-center justify-center bg-zinc-900 text-slate-50">
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen w-full">
        <div className="flex min-h-screen w-full items-start justify-center">
          <div className="flex min-h-screen w-full max-w-5xl flex-col justify-between border-x border-slate-900">
            <header className="flex items-center justify-between bg-slate-800 px-8 py-4">
              <div className="flex items-center">
                <Link
                  href="/"
                  className="flex items-end gap-1 text-xl font-bold tracking-wide"
                >
                  <Image
                    priority
                    src="/images/Streamsave.svg"
                    alt="StreamSave Logo"
                    width={1900}
                    height={3330}
                    className="h-auto w-6"
                  />
                  <h1>treamSave</h1>
                </Link>
              </div>
              {!user.isSignedIn && (
                <SignInButton>
                  <button className="flex items-center justify-center bg-pink-700 px-6 py-2 transition-all hover:scale-105 hover:rounded-md">
                    Sign In
                  </button>
                </SignInButton>
              )}
              {user.isSignedIn && (
                <SignOutButton>
                  <button className="flex items-center justify-center bg-pink-700 px-6 py-2 transition-all hover:scale-105 hover:rounded-md">
                    Sign Out
                  </button>
                </SignOutButton>
              )}
            </header>
            {user.isSignedIn && <Feed />}
            {!user.isSignedIn && user.isLoaded && (
              <>
                <TopSection />
                <MiddleSection />
                <BottomSection />
              </>
            )}
            <footer className="mt-auto">
              <div className="flex flex-col items-center justify-center bg-slate-800 px-8 py-8">
                <p className="text-md text-slate-200">
                  &copy; 2023 StreamSave. All rights reserved.
                </p>
                <p className="text-md text-slate-200">
                  data and images courtesy of{" "}
                  <a
                    className="font-bold underline"
                    href="https://www.themoviedb.org/"
                  >
                    themoviedb.org
                  </a>
                </p>
              </div>
            </footer>
          </div>
        </div>
      </div>
    </div>
  );
}

function Feed() {
  const { data, isLoading, isError } = api.mDB.getTrending.useQuery();
  const rowClasses = "flex gap-4 overflow-x-scroll rounded-lg bg-slate-800 p-4";

  if (isError) return <div>Something went wrong</div>;
  if (!data) return <div>Loading...</div>;

  return (
    <div>
      <MediaRow title={"Trending Shows"} media={data.trendingShows} />
      <MediaRow title={"Popular Shows"} media={data.popularShows} />
      <MediaRow title={"Popular Movies"} media={data.popularMovies} />
    </div>
  );
}

function MediaRow({
  title,
  media,
}: {
  title: string;
  media: MovieAPIResult[] | ShowAPIResult[];
}) {
  return (
    <div>
      <h2>{title}</h2>
      <div>
        <Swiper
          className="w-full"
          modules={[Navigation, Pagination, Scrollbar, A11y]}
          slidesPerView={5}
          loop={true}
          navigation={true}
        >
          {media.map((show) => (
            <SwiperSlide key={show.id}>
              <ShowCard show={show} />
            </SwiperSlide>
          ))}
        </Swiper>
      </div>
    </div>
  );
}

function ShowCard({ show }: { show: ShowAPIResult | MovieAPIResult }) {
  const basePath = "https://image.tmdb.org/t/p/w500";

  const media: { poster_path: string; title: string } = {
    poster_path: show.poster_path,
    title: show.title ? show.title : show.name,
  };

  return (
    <div className="max-w-[194px] border-[1px] border-slate-50 bg-zinc-900 p-2">
      <div className="flex h-[264px] w-44 items-center bg-slate-800">
        <Image
          src={`${basePath}${media.poster_path}`}
          alt=""
          width={176}
          height={264}
          className="object-scale-down"
        />
      </div>
      <div className="p-1">
        <div className="flex h-12 items-center">
          <h3 className="line-clamp-2 text-lg leading-[19px]">{media.title}</h3>
        </div>
        <div className="flex flex-wrap items-center gap-x-2 gap-y-1 pt-1">
          <p className="rounded-full bg-black px-3 text-sm">action</p>
          <p className="rounded-full bg-black px-3 text-sm">drama</p>
          <p className="rounded-full bg-black px-3 text-sm">sci fi</p>
        </div>
      </div>
    </div>
  );
}

function TopSection() {
  return (
    <section className="flex h-full w-full flex-col gap-4 md:flex-row">
      <div className="flex h-full w-full items-center justify-center gap-2 px-12 py-16 md:py-20 lg:py-40">
        <Image
          priority
          src="/images/Streamsave.svg"
          alt="StreamSave Logo"
          width={1900}
          height={3330}
          className="h-auto w-32 object-fill lg:w-80"
        />
        <div className="flex h-full flex-col justify-center gap-2 p-2">
          <div>
            <h1 className="text-3xl font-bold tracking-wider lg:text-5xl">
              Streamsave
            </h1>
            <span className="text-sm text-slate-300">fill your show hole</span>
          </div>

          <SignInButton>
            <button className="flex items-center justify-center bg-pink-700 px-6 py-2 transition-all hover:scale-105 hover:rounded-md">
              Sign In
            </button>
          </SignInButton>
        </div>
      </div>

      <div className="hidden w-full items-center justify-center bg-gradient-to-l from-sky-700 to-transparent py-20 md:flex lg:w-2/3 lg:justify-start lg:py-40 lg:pl-12">
        <p className="w-48 text-center font-bold tracking-wider">
          Organize your favorite shows and movies, or discover new ones!
        </p>
      </div>
    </section>
  );
}

function MiddleSection() {
  return (
    <section className="flex w-full flex-col items-center justify-end bg-gradient-to-tr from-pink-700 via-pink-900 to-zinc-900 px-8 py-16 text-white">
      <div className="flex flex-shrink items-center justify-center gap-2 py-8 md:gap-8 lg:gap-16">
        <Image
          className="h-auto w-[30%] md:w-40"
          src="/images/BreakingBad.png"
          alt=""
          width={144}
          height={290}
        />
        <Image
          className="h-auto w-[30%] md:w-40"
          src="/images/TheOffice.png"
          alt=""
          width={144}
          height={290}
        />
        <Image
          className="h-auto w-[30%] md:w-40"
          src="/images/TheLastOfUs.png"
          alt=""
          width={144}
          height={290}
        />
      </div>
      <h2 className="line-clamp-2 text-center text-2xl font-bold leading-normal tracking-wider md:text-3xl lg:text-5xl">
        Your Favorite Shows & Movies
      </h2>
    </section>
  );
}

function BottomSection() {
  return (
    <section className="flex w-full items-center justify-center bg-gradient-to-bl from-sky-600 via-sky-900 to-zinc-900 px-12 py-4 text-white">
      <div className="flex w-2/3 flex-col items-start justify-center gap-8">
        <h2 className="line-clamp-3 text-2xl font-bold leading-normal tracking-wider md:text-3xl lg:text-5xl  lg:leading-relaxed">
          Organized The Way You Want
        </h2>
        <SignInButton>
          <button className="flex items-center justify-center bg-pink-700 px-6 py-2 transition-all hover:scale-105 hover:rounded-md">
            Sign In
          </button>
        </SignInButton>
      </div>
      <div className="h-auto w-1/2">
        <Image
          src="/images/mobile-list.png"
          alt="How the user's list looks on a mobile device"
          className="py-12"
          width={260}
          height={336}
        />
      </div>
    </section>
  );
}
