import Head from "next/head";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { api } from "~/utils/api";
import Image from "next/image";
import { useEffect, useState } from "react";

export default function Home() {
  const user = useUser();
  const [isClient, setIsClient] = useState(false)
  const { data } = api.post.getAll.useQuery() 

  useEffect(()=>{
    setIsClient(true)
  }, [])

  if(data) console.log(data)
  if(!isClient) return

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="flex min-h-screen flex-col items-center justify-center bg-zinc-900 text-slate-200">

        {/* layout wrapper */}
        <div className="w-screen flex justify-center items-start">
          <div className="max-w-4xl min-h-screen w-full border-x border-slate-900 flex flex-col">

          {/* Header */}
          <header>
            <div className="flex flex-col text-white bg-blue-500">
              {!user.isSignedIn && <SignInButton />}
              {user.isSignedIn && <SignOutButton />}
            </div>
          </header>
         {/* top section */}
          <div 
            className="flex w-full gap-4 h-full" >
            <div className="flex justify-center items-center w-full h-full py-20">
              <Image
                priority
                src="/images/streamsave_logo.png"
                alt="StreamSave Logo"
                width={1900}
                height={3330}
                className="w-44"
              />
            
              <div className="flex flex-col gap-4">

                <div>
                  <h1 className="text-xl lg:text-5xl font-bold text-left leading-3">
                    Fill Your <br />Show Hole<br />
                    <span className="text-lg">w/ StreamSave</span>
                  </h1>
                </div>

                <a
                  data-sveltekit-reload
                  className="flex justify-center items-center px-6 py-2 bg-pink-700"
                  target="_self"
                  href="/signin">Sign in</a
                >
                <a
                  data-sveltekit-reload
                  className="flex justify-center items-center px-6 py-2 bg-sky-600"
                  target="_self"
                  href="/register">Register</a>
              </div>
            </div>      
            <div
              className="w-full lg:w-1/3 flex justify-center lg:justify-start items-center lg:pl-12 py-20 lg:py-40 bg-gradient-to-l from-sky-700 to-transparent"
            >
              <p className="w-48 font-bold text-center">
                Organize your favorite shows and movies, or discover new ones!
              </p>
            </div>
          </div>

          {/*  */}

          <section
  className="bg-gradient-to-tr from-pink-700 via-pink-900 to-zinc-900 w-full text-white flex flex-col justify-end items-center p-16"
>
  <div
    className="flex justify-center items-center flex-wrap gap-2 md:gap-8 lg:gap-16 py-8"
  >
    <img src="/images/BreakingBad.png" alt="" className="w-36" />
    <img src="/images/TheOffice.png" alt="" className="w-36" />
    <img src="/images/TheLastOfUs.png" alt="" className="w-36 hidden md:block" />
  </div>
  <h2 className="text-2xl lg:text-5xl font-bold leading-normal">
    Your Favorite Shows & Movies
  </h2>
</section>

{/*  */}

<section
  className="bg-gradient-to-bl from-sky-600 via-sky-900 to-zinc-900 w-full flex justify-center items-center text-white p-4"
>
  <div className="flex flex-col justify-center items-start gap-8">
    <h2 className="text-2xl lg:text-5xl font-bold leading-normal">
      Organized How<br />You Want
    </h2>
    <a
      data-sveltekit-reload
      href="/register"
      className="transition-all hover:scale-125 hover:rounded-md px-6 py-2 bg-pink-600 text-slate-100"
      >Start Your List!</a
    >
  </div>
  <img
    src="/images/mobile-list.png"
    alt="How the user's list looks on a mobile device"
    className="w-60 lg:w-[30rem] py-12"
  />
</section>


          {/* layout wrapper */}
          </div>  
        </div>

      </body>
    </>
  );
}
