name: Query MongoDB

on:
  schedule:
    - cron: "0 0 */2 * *" # Every other day at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  query:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Specify your desired Node.js version

      - name: Install dependencies
        run: |
          npm install mongodb

      - name: Run MongoDB query
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }} # Store your MongoDB URI in GitHub Secrets
        run: node query.js
