name: Query MongoDB

on:
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:

jobs:
  query:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install mongodb

      - name: Run MongoDB query
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: node query.js
